<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>



  <ItemGroup>
    <Folder Include="Features\Commands\CategoriesCommand\" />
    <Folder Include="Features\Commands\UsersRolesCommand\" />
    <Folder Include="Features\Handlers\Move_TypesHandler\" />
    <Folder Include="Features\Handlers\UserRolesHandler\" />
    <Folder Include="Features\Queries\Move_TypesQuery\" />
    <Folder Include="Features\Queries\UserRolesQuery\" />
    <Folder Include="Features\Results\Move_TypesResult\" />
    <Folder Include="Features\Results\UserRolesResult\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventory_Management.Domain\Inventory_Management.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Inventory_Management.Persistance\Inventory_Management.Persistance.csproj" />
  </ItemGroup>

</Project>
